name: 'github-action-todo-commenter'
description: Parses pull request files based on tags and creates a comment with a task list
author: Georgios Kampitakis
runs:
  using: 'node12'
  main: 'lib/index.js'
branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  github-token:
    required: true
    description: Github Token for Github API requests.
  review-message:
    required: false
    description: >
      [String] You can specify a message at the end of the comment.
      It will tag the creator of pull request
  tags:
    required: false
    description: >
      [String comma separated] Keywords that the parser will try to identify for creating comments.
      Default tags are TODO:,FIXME:,BUG:
  ignore-pattern:
    required: false
    description: '[Regex] Regex used for filtering files out from parsing.'
  multiline-comments:
    required: false
    description: '[Boolean] if true the action will create one comment per line instead of one comment'
  comment-title:
    required: false
    description:  >
      [String] If the action is in single-comment mode you can specify a title.