name: test
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test action locally
        uses: gkampitakis/github-action-todo-commenter@test2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }} #FIXME: